#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/mobility-module.h"
#include "ns3/wifi-module.h"
#include "ns3/internet-module.h"
#include "ns3/applications-module.h"
#include "ns3/flow-monitor-module.h"

#include <iostream>
#include <fstream>
using namespace ns3;

int main(int argc, char *argv[])
{
    // =========================================
    // 1. CREATE NODES
    // =========================================

    NodeContainer uav;
    uav.Create(1);

    NodeContainer users;
    users.Create(10);

    // =========================================
    // 2. 3D MOBILITY / POSITIONS
    // =========================================

    MobilityHelper mobility;

    mobility.SetMobilityModel(
        "ns3::ConstantPositionMobilityModel");

    // UAV position
    Ptr<ListPositionAllocator> uavPosition =
        CreateObject<ListPositionAllocator>();

    // Read UAV position generated by ML
double uavX, uavY, uavZ;

std::ifstream positionFile("data/uav_positions.json");

if (!positionFile)
{
    std::cerr << "Could not open data/uav_positions.json" << std::endl;
    return 1;
}

// Minimal JSON parsing (no external deps) for the ML handoff file:
//   "uav_positions":  [[x, y, z]]
//   "user_positions": [[x, y, z], [x, y, z], ...]
// The file is pretty-printed, so we locate values by key rather than by
// assuming a compact "[[" layout.

std::string line;
std::string json;

while (std::getline(positionFile, line))
{
    json += line;
}

size_t uavKey = json.find("\"uav_positions\"");

if (uavKey == std::string::npos)
{
    std::cerr << "Could not find \"uav_positions\" in data/uav_positions.json" << std::endl;
    return 1;
}

size_t uavBracket = json.find('[', uavKey);            // outer '['
if (uavBracket != std::string::npos)
{
    uavBracket = json.find('[', uavBracket + 1);       // first inner '['
}

if (uavBracket == std::string::npos ||
    sscanf(json.c_str() + uavBracket + 1,
           "%lf, %lf, %lf",
           &uavX,
           &uavY,
           &uavZ) != 3)
{
    std::cerr << "Could not parse UAV coordinates from data/uav_positions.json" << std::endl;
    return 1;
}

std::cout << "ML UAV Position: ("
          << uavX << ", "
          << uavY << ", "
          << uavZ << ")"
          << std::endl;

uavPosition->Add(
    Vector(uavX, uavY, uavZ));

    mobility.SetPositionAllocator(uavPosition);
    mobility.Install(uav);

    // Ground users: use the SAME positions that Sionna RT / PPO evaluated,
    // handed over through data/uav_positions.json as
    //   "user_positions": [[x, y, z], ...].
    // This keeps the wireless-propagation scenario and the network
    // simulation consistent. If the field is absent (older handoff file),
    // fall back to the previous generated layout.
    Ptr<ListPositionAllocator> userPositions =
        CreateObject<ListPositionAllocator>();

    uint32_t usersLoaded = 0;
    size_t userKey = json.find("\"user_positions\"");

    if (userKey != std::string::npos)
    {
        size_t arrStart = json.find('[', userKey);          // outer '['

        // Find the matching close bracket of the outer array by depth
        // counting (whitespace-tolerant for pretty-printed JSON).
        size_t arrEnd = std::string::npos;
        if (arrStart != std::string::npos)
        {
            int depth = 0;
            for (size_t k = arrStart; k < json.size(); k++)
            {
                if (json[k] == '[')
                {
                    depth++;
                }
                else if (json[k] == ']')
                {
                    depth--;
                    if (depth == 0)
                    {
                        arrEnd = k;
                        break;
                    }
                }
            }
        }

        size_t p = (arrStart == std::string::npos)
                       ? std::string::npos
                       : json.find('[', arrStart + 1);      // first inner '['

        while (p != std::string::npos && arrEnd != std::string::npos &&
               p < arrEnd && usersLoaded < users.GetN())
        {
            double ux, uy, uz;
            if (sscanf(json.c_str() + p + 1,
                       "%lf, %lf, %lf",
                       &ux, &uy, &uz) == 3)
            {
                userPositions->Add(Vector(ux, uy, uz));
                usersLoaded++;
            }
            p = json.find('[', p + 1);
        }
    }

    if (usersLoaded != users.GetN())
    {
        std::cerr << "WARNING: expected " << users.GetN()
                  << " entries in \"user_positions\", found " << usersLoaded
                  << "; using generated fallback positions." << std::endl;

        userPositions = CreateObject<ListPositionAllocator>();
        for (uint32_t i = 0; i < users.GetN(); i++)
        {
            userPositions->Add(
                Vector(uavX + i * 5.0,
                       uavY + i * 3.0,
                       0.0));
        }
    }
    else
    {
        std::cout << "Loaded " << usersLoaded
                  << " ground-user positions from data/uav_positions.json"
                  << std::endl;
    }

    mobility.SetPositionAllocator(userPositions);
    mobility.Install(users);

    // =========================================
    // 3. WIFI
    // =========================================

    NodeContainer allNodes;

    allNodes.Add(uav);
    allNodes.Add(users);

    WifiHelper wifi;

    wifi.SetStandard(WIFI_STANDARD_80211n);

    WifiMacHelper wifiMac;

    wifiMac.SetType(
        "ns3::AdhocWifiMac");

    // Wi-Fi channel
    YansWifiChannelHelper channel =
        YansWifiChannelHelper::Default();

    YansWifiPhyHelper phy;

    phy.SetChannel(channel.Create());

    // Increase transmission power
    phy.Set(
        "TxPowerStart",
        DoubleValue(30.0));

    phy.Set(
        "TxPowerEnd",
        DoubleValue(30.0));

    // Improve receiver sensitivity
    phy.Set(
        "RxSensitivity",
        DoubleValue(-90.0));

    NetDeviceContainer devices =
        wifi.Install(
            phy,
            wifiMac,
            allNodes);

    // =========================================
    // 4. INTERNET STACK
    // =========================================

    InternetStackHelper internet;

    internet.Install(allNodes);

    Ipv4AddressHelper address;

    address.SetBase(
        "10.1.1.0",
        "255.255.255.0");

    Ipv4InterfaceContainer interfaces =
        address.Assign(devices);

    // =========================================
    // 5. UDP SERVER ON UAV
    // =========================================

    uint16_t port = 9000;

    UdpServerHelper server(port);

    ApplicationContainer serverApp =
        server.Install(uav.Get(0));

    serverApp.Start(
        Seconds(1.0));

    serverApp.Stop(
        Seconds(10.0));

    // =========================================
    // 6. UDP CLIENTS ON USERS
    // =========================================

    for (uint32_t i = 0;
         i < users.GetN();
         i++)
    {
        UdpClientHelper client(
            interfaces.GetAddress(0),
            port);

        client.SetAttribute(
            "MaxPackets",
            UintegerValue(1000));

        client.SetAttribute(
            "Interval",
            TimeValue(
                MilliSeconds(10)));

        client.SetAttribute(
            "PacketSize",
            UintegerValue(512));

        ApplicationContainer clientApp =
            client.Install(
                users.Get(i));

        clientApp.Start(
            Seconds(2.0));

        clientApp.Stop(
            Seconds(10.0));
    }

    // =========================================
    // 7. FLOW MONITOR
    // =========================================

    FlowMonitorHelper flowmon;

    Ptr<FlowMonitor> monitor =
        flowmon.InstallAll();

    // =========================================
    // 8. RUN SIMULATION
    // =========================================

    Simulator::Stop(
        Seconds(10.0));

    Simulator::Run();

    // =========================================
    // 9. COLLECT RESULTS
    // =========================================

    monitor->CheckForLostPackets();

    Ptr<Ipv4FlowClassifier> classifier =
        DynamicCast<Ipv4FlowClassifier>(
            flowmon.GetClassifier());

    auto stats =
        monitor->GetFlowStats();

    std::cout
        << "\n====================================\n";

    std::cout
        << "       UAV NETWORK RESULTS\n";

    std::cout
        << "====================================\n";

    for (const auto &flow : stats)
    {
        Ipv4FlowClassifier::FiveTuple tuple =
            classifier->FindFlow(flow.first);

        std::cout
            << "\nFlow: "
            << tuple.sourceAddress
            << " -> "
            << tuple.destinationAddress
            << "\n";

        if (flow.second.rxPackets == 0)
        {
            std::cout
                << "No packets received.\n";

            continue;
        }

        double duration =
            flow.second.timeLastRxPacket.GetSeconds()
            -
            flow.second.timeFirstTxPacket.GetSeconds();

        double throughput = 0.0;

        if (duration > 0)
        {
            throughput =
                flow.second.rxBytes * 8.0
                /
                duration
                /
                1000000.0;
        }

        double delay =
            flow.second.delaySum.GetSeconds()
            /
            flow.second.rxPackets
            *
            1000.0;

        double packetLoss =
            100.0
            *
            (
                flow.second.txPackets
                -
                flow.second.rxPackets
            )
            /
            flow.second.txPackets;

        std::cout
            << "Packets Sent: "
            << flow.second.txPackets
            << "\n";

        std::cout
            << "Packets Received: "
            << flow.second.rxPackets
            << "\n";

        std::cout
            << "Throughput: "
            << throughput
            << " Mbps\n";

        std::cout
            << "Average Delay: "
            << delay
            << " ms\n";

        std::cout
            << "Packet Loss: "
            << packetLoss
            << " %\n";
    }

    std::cout
        << "\n====================================\n";

    // =========================================
    // 10. DESTROY SIMULATION
    // =========================================

    Simulator::Destroy();

    return 0;
}
